<a href="https://colab.research.google.com/github/xxnyang/class_repo/blob/chap2/ch2_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [18]:
x=tf.constant(np.array([1.,4.,3.]).reshape(1,3),dtype=tf.float32)
W=tf.Variable(tf.random.uniform((3,2)),dtype=tf.float32)
b=tf.Variable(tf.zeros((2,)),dtype=tf.float32)

In [19]:
print(x)
print(W)
print(b)

tf.Tensor([[1. 4. 3.]], shape=(1, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.8643838 , 0.9756776 ],
       [0.32137024, 0.7948295 ],
       [0.8126557 , 0.83936083]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [20]:
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [21]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [4., 4.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>]

In [ ]:
########### 밑은 수정 필요 ################33

In [26]:
with tf.GradientTape() as tape:
    y3 = tf.pow(y, 3)
grad_of_y3_wrt_W = tape.gradient(y3, W)

In [27]:
print(grad_of_y3_wrt_W)

None


In [24]:
with tf.GradientTape() as tape:
    y3 = tf.pow(y, 3)
grad_of_y3_wrt_b = tape.gradient(y3, b)

In [25]:
grad_of_y3_wrt_b